<a href="https://colab.research.google.com/github/ola8499/genderClassification/blob/main/genderClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Gender Classification

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

###Exploring dataset

In [3]:
df_gender = pd.read_csv("/content/gender_classification.csv")
df_gender.head()

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female

In [4]:
df_gender.shape

(5001, 8)

In [6]:
df_gender.columns

Index(['long_hair', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide',
       'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'gender'],
      dtype='object')

In [7]:
df_gender.dtypes

long_hair                      int64
forehead_width_cm            float64
forehead_height_cm           float64
nose_wide                      int64
nose_long                      int64
lips_thin                      int64
distance_nose_to_lip_long      int64
gender                        object
dtype: object

In [8]:
df_gender["gender"].value_counts()

Female    2501
Male      2500
Name: gender, dtype: int64

###Cleaning Data

In [9]:
df_gender.isnull().any()

long_hair                    False
forehead_width_cm            False
forehead_height_cm           False
nose_wide                    False
nose_long                    False
lips_thin                    False
distance_nose_to_lip_long    False
gender                       False
dtype: bool

###Preprocessing Data

In [10]:
import sklearn
from sklearn import preprocessing

In [13]:
gender_encoding = preprocessing.LabelEncoder()
df_gender['gender'] = gender_encoding.fit_transform(df_gender['gender'].astype(str))
df_gender.head()
# Female:0 Male:1

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,1
1,0,14.0,5.4,0,0,1,0,0
2,0,11.8,6.3,1,1,1,1,1
3,0,14.4,6.1,0,1,1,1,1
4,1,13.5,5.9,0,0,0,0,0

###Visualization Data

In [14]:
pd.crosstab(df_gender["long_hair"],df_gender["gender"])

gender        0     1
long_hair
0           317   335
1          2184  2165

In [17]:
pd.crosstab(df_gender["nose_wide"],df_gender['gender'])

gender        0     1
nose_wide
0          2214   317
1           287  2183

In [18]:
pd.crosstab(df_gender["nose_long"],df_gender["gender"])

gender        0     1
nose_long
0          2161   300
1           340  2200

In [19]:
pd.crosstab(df_gender["lips_thin"],df_gender["gender"])

gender        0     1
lips_thin
0          2197   338
1           304  2162

In [20]:
pd.crosstab(df_gender["distance_nose_to_lip_long"],df_gender["gender"])

gender                        0     1
distance_nose_to_lip_long
0                          2197   309
1                           304  2191